services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - db_data:/app/prisma
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    driver: bridge
